### ISSUE TITLE
SLC List Check Error in EZ_InSAR Software

### ISSUE THREAD

**Issue by Elcappo2019** [alexisInSAR/EZ-InSAR#67]
Description:

I am encountering an issue while using the EZ_InSAR software. Here are the steps I've taken:

Installed all packages and initiated the EZ_InSAR interface.
Created a KML file for my study area, set the Path number, Flight direction, and specified the period interval.
Modified the pathinformation.txt file with my ASF credentials (ASFID and ASFPWD), and tested the account successfully on [ASF Search](https://search.asf.alaska.edu/#/).
Clicked on "Check SLC list," but encountered the following error:

**" Error using createlistSLC>@(rep)strrep(M.AcquisitionDate,'Z',rep) (line 120)
Unrecognized table variable name 'AcquisitionDate'.
Error in createlistSLC (line 120)
    a = cellfun(@(rep) strrep(M.AcquisitionDate,'Z',rep), {''}, 'UniformOutput', false);
Error in manageSLC (line 39)
    createlistSLC([],[],[],miesar_para);
Error in GUIMIESAR>@(src,evt,arg1,arg2)manageSLC(src,evt,'checking',figmiesar.UserData) (line 231)
btslccheck.ButtonPushedFcn = @(src,evt,arg1,arg2) manageSLC(src,evt,'checking',figmiesar.UserData);
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 386)
Error while evaluating Button PrivateButtonPushedFcn. "**

                                                             Any guidance on resolving this issue would be highly appreciated.

Additional Information:

Operating System: [Ubuntu 22.04.3 LTS]
Matlab version: [ R2020_b]

![EZ_InSAR](https://github.com/alexisInSAR/EZ-InSAR/assets/45139381/a5538dd5-e70c-4fc9-9dbb-ee25c64470b9)

**Comment by alexisInSAR** [comment]
Hi, 

What is your version of EZ-InSAR?

**Comment by FranckzGithub** [comment]
I am facing the same problem, a few days ago it was working, but now is not working, maybe is a problem with the API? even i runned in linux command line: curl https://api.daac.asf.alaska.edu/services/search/param?platform=Sentinel-1A\&beamMode=IW\&bbox=-68.231,-16.6733,-67.9672,-16.3895\&start=2018-01-01T00:00:00UTC\&end=2020-12-31T00:00:00UTC\&relativeOrbit=76\&flightDirection=A\&processingLevel=SLC\&maxResults=10000\&output=csv > tmp_list_SLC.csv    but is not working, as i told you this same command line it was working a few days ago, but now... no, why?

**Comment by FranckzGithub** [comment]
it was a problem of the API in my case, now is working.... whole day was not working

**Comment by A220N1** [comment]
Hi,

I encountered a similar error as well.


##  **Check the SLC's error**

**Version of EZ-InSAR**: [2.1.0]

**Operating System**: [I run all in wsl2 (ubuntu 22.04) ; MATLAB R2023B]

**Description of the Problem**:

I encountered an issue while using EZ_InSAR. Here are the steps I followed:

1. Installed all required packages and initiated the EZ_InSAR interface.
![ezinsar_wsl2](https://github.com/alexisInSAR/EZ-InSAR/assets/46009455/493645e2-9add-48bd-a107-7a2a32648d99)

2. Modified the `pathinformation.txt` file with my ASF credentials (ASFID and ASFPWD), and tested the account successfully on ASF Search.

3. Created a KML file for my study area and set the necessary SLC parameters.
![ezinsar_webmap](https://github.com/alexisInSAR/EZ-InSAR/assets/46009455/0686c9f7-90ef-4e52-9d7b-9c78a02463b5)

4. Clicked on "Check SLC's"

**Error Message**:

![ezinsar_matlab](https://github.com/alexisInSAR/EZ-InSAR/assets/46009455/d8f5571e-a49b-4fbd-bbfe-2eb6b375673e)


I don't think it's an issue with ASF because I was able to download products by logging into the website, but I noticed that another user, FranckzGithub, mentioned that he had a similar issue caused by a problem with the API. FranckzGithub, could you please provide more details about how you resolved the issue or any additional information that might be helpful?

Also, for completeness, the slc csv is created, with the complete list of data for the date range I want. : 


[tmp_list_SLC.csv](https://github.com/alexisInSAR/EZ-InSAR/files/13377792/tmp_list_SLC.csv)

**Comment by A220N1** [comment]
# Locale Configuration and CSV Parsing Error in MATLAB
 
## Issue Update
*I am providing additional details on my environment setup, specifically the locale configuration, as it might be related to the error encountered while parsing CSV files in MATLAB.*

## Locale Details
*My WSL2 environment is fully set to `en_US.UTF-8` across all parameters, as confirmed by the `locale` command. Despite this, MATLAB seems to misinterpret the period (`.`) as a decimal separator instead of recognizing the comma (`,`) as the delimiter when reading CSV files, leading to the "Unrecognized table variable name 'AcquisitionDate'" error (refer to the provided screenshot).*

## Additional Details: CSV Delimiter Impact on Reading Files

When attempting to read a CSV file without specifying the delimiter, MATLAB does not recognize the column headers and results in an error:

```matlab
>> data = readtable('tmp_list_SLC.csv');
>> data.AcquisitionDate
Error using  . 
Unrecognized table variable name 'AcquisitionDate'.
```
However, when specifying the comma delimiter, MATLAB correctly identifies the column names and reads the data as expected:
```
>> data = readtable('tmp_list_SLC.csv', 'Delimiter', ',');
Warning: Column headers from the file were modified to make them valid MATLAB identifiers before creating variable names for the
table. The original column headers are saved in the VariableDescriptions property.
Set 'VariableNamingRule' to 'preserve' to use the original column headers as table variable names. 
>> data.AcquisitionDate

ans =

  18×1 cell array

    {'2023-11-12T18:59:57.405455Z'}
    {'2023-11-12T18:59:32.576390Z'}
    ...
    {'2023-08-08T18:59:55.081051Z'}
    {'2023-08-08T18:59:30.264320Z'}
```
This behavior indicates that the issue lies with MATLAB's default delimiter settings, which do not align with the locale configuration of en_US.UTF-8 where the comma is expected to be the list separator

## Seeking Solution
*Given the locale settings, MATLAB should not require the explicit specification of a comma delimiter for CSV operations. I am seeking a solution to ensure MATLAB adheres to the `en_US.UTF-8` locale settings for file reading functions by default, without needing to manually specify the delimiter each time.*

**Comment by Elcappo2019** [comment]
> Hi,
> 
> What is your version of EZ-InSAR?

Sorry for delay in reply, I used  " EZ-InSAR-Version_2_1_0_Beta"

**Comment by alexisInSAR** [comment]
Hi, 

We hope that the new version (2.2.0) will solve your problem. 

Kind regards, 

Alexis
